### ISSUE TITLE
[BUG]-Selenium tests do not run

### ISSUE THREAD

**Issue by kiinami** [EGC-Serranito/serranito-hub#89]
### Summary

Selenium tests merged into main and develop do not run because they do not follow the structure in the project for them.

### Steps to Reproduce

1. Clone repo
2. Setup local environment
3. Run `rosemary selenium`

### Expected result

The Selenium tests run

### Actual result

The Selenium tests just exit without running, or in the case of Fakenodo, give errors

### Priority

None

### Operating System

Linux

### Browser

Chrome

### Application Version

2.2.1

### Other eenvironment details

Both in the `main` and  `develop`

**Comment by Dangalcan** [comment]
Hi kinami. It is a pleasure recieving your feedback. Unfortunately, main branch is not updated yet. We will try to do some research about your issue.  Just in case you are refering that Selenium tests dont run, it is not true. In fact they are running but without showing the UI. We thought that was more confortable so we could do other things without having a lot of pop ups. Anyways you will have news pretty soon.  Thanks again.
